export { AuthModule } from './auth'
export { UserModule } from './user'
// export { GdprDbModule } from './gdpr'
// export { VehicleModule } from './vehicle'
// export { VehicleOwnerModule } from './vehicle.owner'
// export { RecyclingRequestModule } from './recycling.request'
// export { RecyclingPartnerDbModule } from './recycling.partner'
// export { SamgongustofaModule } from './samgongustofa'
// export { FjarsyslaModule } from './fjarsysla'
